length = 1000

[[effects]]
op = "scale"
x_factor = "1..2"
y_factor = "1..0.8"
loop = "pingpong"
ease = "ease-in-out"

[[effects]]
op = "scale"

[[effects]]
op = "multiply-all"
r = "0..2"
g = "0..1"
b = "0..1"
ease = "ease-in-out"
loop = "pingpong"

[[effects]]
op = "rotate"
angle = "0..15"
end = 0.5
ease = "ease-in-out"
loop = "pingpong"

[[effects]]
op = "rotate"
angle = "0..-15"
start = 0.5
ease = "ease-in-out"
loop = "pingpong"
